replicaCount: 1

image:
  repository: ghcr.io/ipvz/trip_frontend
  pullPolicy: IfNotPresent
imagePullSecrets: [ ]

podAnnotations: { }
podSecurityContext: { }
securityContext: { }

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: trip.ipvz.ml
      paths:
        - path: /
          pathType: Prefix
  tls: []

config:
  mountPath: /etc/nginx/conf.d
  value:
    api.locations: |
      upstream Backend {
          server trip-gateway.ipvz.ml;
      }
      location /api {
          proxy_pass http://api-gateway/api;
      }
      location /test {
          proxy_pass http://Backend/api;
      }

secret:
  mountPath: /etc/secret
  value:
    example: test

tls:
  crt: "crt"
  key: "key"

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

probe:
  readiness:
    path: /
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  liveness:
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  startup:
    failureThreshold: 30
    periodSeconds: 10
    successThreshold: 1

nodeSelector: { }
tolerations: [ ]
affinity: { }
