replicaCount: 1

image:
  repository: ghcr.io/ipvz/trip_frontend
  pullPolicy: IfNotPresent
imagePullSecrets: [ ]

podAnnotations: { }
podSecurityContext: { }
securityContext: { }

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: trip.ipvz.ml
      paths:
        - path: /
          pathType: Prefix
  tls: []

config:
  mountPath: /etc/nginx/sites-enabled
  value:
    trip-apps.conf: |
      upstream Backend {
          server trip-gateway.ipvz.ml;
      }
      server {
          listen 80;
          listen [::]:80;
      
          proxy_redirect off;
          proxy_read_timeout 180s;
          proxy_send_timeout 180s;
          proxy_connect_timeout 180s;
          proxy_buffering on;
          client_max_body_size 128m;
      
          location /hc {
              proxy_pass http://Backend/actuator/health;
          }
      }

secret:
  mountPath: /etc/secret
  value:
    example: test

tls:
  crt: "crt"
  key: "key"

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

probe:
  readiness:
    path: /
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  liveness:
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  startup:
    failureThreshold: 30
    periodSeconds: 10
    successThreshold: 1

nodeSelector: { }
tolerations: [ ]
affinity: { }
