replicaCount: 1

image:
  repository: ghcr.io/ipvz/trip_api-gateway
  pullPolicy: IfNotPresent
imagePullSecrets: [ ]

podAnnotations: { }
podSecurityContext: { }
securityContext: { }

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hosts:
    - host: trip-gateway.ipvz.ml
      paths:
        - path: /api
          pathType: Prefix
  tls: []

config:
  mountPath: /etc/config
  value:
    spring:
      application:
        name: api-gateway
    server:
      port: 8181
    client:
      auth:
        uri: http://authenticate:80

secret:
  mountPath: /etc/secret
  value:
    example: test

tls:
  crt: "crt"
  key: "key"

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

probe:
  readiness:
    path: /actuator/health/readiness
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  liveness:
    path: /actuator/health/liveness
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  startup:
    path: /actuator/health/liveness
    failureThreshold: 30
    periodSeconds: 10
    successThreshold: 1

nodeSelector: { }
tolerations: [ ]
affinity: { }
