apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  Config.yaml: |-
    {{- toYaml .Values.config.value | nindent 4 }}
